### ISSUE TITLE
Bazel ImportError on macOS 12.2 Monterey with Intel chip

### ISSUE THREAD

**Issue by JGoDC** [deepmind/code_contests#5]
Please help with Bazel ImportError on macOS 12.2 Monterey with Intel chip:

``
% bazel run -c opt \
  :print_names_and_sources /tmp/dm-code_contests/code_contests_valid.riegeli
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:print_names_and_sources (82 packages loaded, 2025 targets configured).
INFO: Found 1 target...
Target //:print_names_and_sources up-to-date:
  bazel-bin/print_names_and_sources
INFO: Elapsed time: 4.780s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_j/651bc297ae9686f74aa6889e91cbfc4c/execroot/__main__/bazel-out/darwin-opt/bin/print_names_and_sources.runfiles/__main__/print_names_and_sources.py", line 24, in <module>
    import riegeli
  File "/private/var/tmp/_bazel_j/651bc297ae9686f74aa6889e91cbfc4c/execroot/__main__/bazel-out/darwin-opt/bin/print_names_and_sources.runfiles/com_google_riegeli/python/riegeli/__init__.py", line 18, in <module>
    from riegeli.records import record_reader
ImportError: dlopen(/private/var/tmp/_bazel_j/651bc297ae9686f74aa6889e91cbfc4c/execroot/__main__/bazel-out/darwin-opt/bin/print_names_and_sources.runfiles/com_google_riegeli/python/riegeli/records/record_reader.so, 0x0002): symbol not found in flat namespace '__ZNK11highwayhash11HighwayHashILj2EEclERA4_KyPKcmPy'
``

% bazel --version
bazel 5.0.0-homebrew
% python -V
Python 3.7.9
% uname -m
x86_64

Thanks!

**Comment by KareemAlaa2001** [comment]
Getting the same exact error here as well, would be nice to get some kind of response on the open issues...

**Comment by davidhchoi** [comment]
Can you check the Python 2 and compiler versions as well? And update them if necessary.

https://github.com/tensorflow/tensorflow/issues/39521 may also be related.

**Comment by Luowaterbi** [comment]
I have the same problem on M1pro.

**Comment by felixgimeno** [comment]
Can you try on Linux or bazel version 6.0.0 ?

**Comment by isaacgor216** [comment]
Has anyone found a solution or workaround to this?
