### ISSUE TITLE
Error - bazel run

### ISSUE THREAD

**Issue by karlie38** [deepmind/code_contests#9]
Python 3.9.7 
OS: Window

**Having an error when running bazel to read RIEGELI files.**

I followed the readme (install google sdk -> download data using 'gsutil' -> git clone code_contests -> 
`
bazel run -c opt :print_names_and_sources C:\tmp\dm-code_contests\dm-code_contests/code_contests_valid.riegeli
` 
).
I saw same issue with me (https://github.com/deepmind/code_contests/issues/4)  and saw the answer of suggesting change of python version (3.x -> 2.x). But, **"local variable 'python_include' is referenced before assignment"** error also happened  and I thought this problem and version issue have to be fixed.

![image](https://user-images.githubusercontent.com/56949426/156873740-76bb2b89-e174-4f05-91e3-3db9ff2882f8.png)

Is there any way to read RIEGELI files easily?

**Comment by PhungVanDuy** [comment]
I just resolved this problem, you should make sure your gcc is a recent new version (my system with gcc-7.5 on Ubuntu 16.04). 

In terms of python2 you also should install like this: 
1. Remove bazel and reinstall 
```bash
bazel clean --expunge
rm -rf ~/.cache/bazel
```

You can re-install follow this [instruction](https://docs.bazel.build/versions/main/install-ubuntu.html)

2. Install python2 dependency 
```bash
sudo apt update && sudo apt install python-dev
```

**Comment by davidhchoi** [comment]
Do the above instructions work for you? In particular, you need to install *both* Python 3 and Python 2, and this is a not a problem that can be fixed in the repo itself.

**Comment by PhungVanDuy** [comment]
@davidhchoi  I get this when I try to run execution/evalutation code, it's seems missing this file `contest_problem.pb.h` 
![Screen Shot 2022-03-22 at 06 13 00](https://user-images.githubusercontent.com/28798474/159379078-daf0d40b-d22b-4adb-8340-f0d97d92b495.png)

Can you check this one?

**Comment by karlie38** [comment]
My python version is 3.x and my gcc version is latest.
I also tested it in another environment (Ubuntu. 18.04 & Python version 3.x ). It worked when I followed the guide. However, in Window environment, it didn't work.

**Comment by davidhchoi** [comment]
@karlie38 what is your Python 2 version? Can you check that Python 2 is installed as well as Python 3?

@PhungVanDuy what is your bazel version, exact command line, and local changes (if any)? That is a proto file that should be automatically compiled into a header file by bazel.

**Comment by davidhchoi** [comment]
For  your first question, is it possible to try this directly on a Linux machine? Or does this happen outside of a notebook? It might be possible that creating the header for the proto fails for some reason (e.g. the build directory is not writeable). I assume `load_data_test.cc` also fails.

For the second, it's possible, but we might wait to learn a little bit more what issues people run into. I think specifying bazel/python 2/python 3/clang versions covers all issues currently (plus that we can't currently support non-Linux systems).

**Comment by PhungVanDuy** [comment]
@davidhchoi  I have success to build execution code, I have a question that you have any plan to release code for CPP solution testing? As I known that currently this only support Python Solution right?

**Comment by davidhchoi** [comment]
The C++ sandbox is significantly more complicated, and more coupled with internal tools, so while we may release it in the future we currently can't promise anything. I think any kind of sandbox will work though; the main purpose of releasing solution testing is to demonstrate how the output checking works in case it isn't clear from the paper, rather than releasing all the sandboxes we use.

That said, I think we'd welcome pull requests to add a C++ sandbox (and also giving instructions for colab, other OSs, a docker image, etc. as asked in your last question)

**Comment by PhungVanDuy** [comment]
@davidhchoi  thank you for your information, I just need to asked because if we have completely sandbox for test maybe it's can help on some ideas to use RL to guidance decoder  with execution score as  a part of reward.

**Comment by davidhchoi** [comment]
RL to guide the encoder is an interesting idea, but I think Python evaluation should be enough to get you quite far on this so you can see if it's viable before investing in C++.

**Comment by PhungVanDuy** [comment]
Hi @davidhchoi , 

I am working on few ideas to improve AlphaCode so I have few research question that I want to discuss with you, if you don't mind can you give me your contact? It would be my pleasure to speak to you directly via email/discord or slack. Looking for your response.

Thanks.

**Comment by davidhchoi** [comment]
Sure. My contact information is in the [AlphaCode paper](https://arxiv.org/pdf/2203.07814.pdf). You can reach me at davidhchoi at deepmind.com.

**Comment by PhungVanDuy** [comment]
@davidhchoi  thank you for your information, I have sent you an email via duyphung.ai@gmail.com. Looking for your response.

**Comment by DanialZohairen** [comment]
> Do the above instructions work for you? In particular, you need to install _both_ Python 3 and Python 2, and this is a not a problem that can be fixed in the repo itself.

I already have installed both python2 and python3 and I'm still getting the same error. I'm working on a windows10

**Comment by karlie38** [comment]
@DanialZohairen  It didn't work out for me in window environment. I did it in Ubuntu. 18.04 & Python version 3.x ).

**Comment by davidhchoi** [comment]
Yes, as mentioned in https://github.com/deepmind/code_contests#supported-platforms we have only tested this on Linux, and aren't able to test this on other platforms like Windows. If someone manages to get it working on Windows though, we'd be happy to update the documentation with instructions.

**Comment by LaudemPax** [comment]
@karlie38 may I know which versions of gcc and bazel you used? I'm trying to create a docker image for this but I keep getting this error with gcc:

![image](https://user-images.githubusercontent.com/2220314/170846856-1228fca8-a040-4a9f-946d-631b16c60fd4.png)

**Comment by karlie38** [comment]
My system has updated and i'm not sure about gcc version, but bazel version was bazel-5.0.0 and gcc version was 9.3.0. @LaudemPax

**Comment by LaudemPax** [comment]
In case anyone else needs it, I made a docker container as a workaround to get the bazel build working on Windows. Its on [Docker Hub](https://hub.docker.com/repository/docker/laudempax/deepmind-bazel/general) and has been used to train a model with the code_contests dataset on windows.

**Comment by wvaughn409** [comment]
> In case anyone else needs it, I made a docker container as a workaround to get the bazel build working on Windows. Its on [Docker Hub](https://hub.docker.com/repository/docker/laudempax/deepmind-bazel/general) and has been used to train a model with the code_contests dataset on windows.

I tried out your Docker container, thank you by the way for doing that, but the command cannot seem to find the local .riegeli file I'm referencing:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\code_contests-main/tmp/dm-code_contests/code_contests_valid.riegeli'

Here is the modified command I executed from terminal:
docker run -it -v %cd%:/build -w /build laudempax/deepmind-bazel:ubuntu-20.04 run -c opt :print_names_and_sources %cd%/tmp/dm-code_contests/code_contests_valid.riegeli

`C:\code_contests-main>docker run -it -v %cd%:/build -w /build laudempax/deepmind-bazel:ubuntu-20.04 run -c opt :print_names_and_sources %cd%/tmp/dm-code_contests/code_contests_valid.riegeli
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_github_grpc_grpc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "987ea637191b99f61ef24c54315c6eb7457eac11107513da1562bd2213163bde"
DEBUG: Repository com_github_grpc_grpc instantiated at:
  /build/WORKSPACE:5:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //:print_names_and_sources (86 packages loaded, 2023 targets configured).
INFO: Found 1 target...
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/descriptor_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/timestamp_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/wrappers_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/struct_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/source_context_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/duration_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/field_mask_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/compiler/plugin_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/type_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/api_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/empty_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_riegeli/python/riegeli/records/records_metadata_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From Compiling riegeli/records/record_reader.cc:
In file included from external/com_google_absl/absl/container/inlined_vector.h:54,
                 from external/com_google_absl/absl/strings/cord.h:78,
                 from external/com_google_riegeli/riegeli/records/record_reader.h:27,
                 from external/com_google_riegeli/riegeli/records/record_reader.cc:15:
external/com_google_absl/absl/container/internal/inlined_vector.h: In constructor 'riegeli::RecordReaderBase::RecordReaderBase()':
external/com_google_absl/absl/container/internal/inlined_vector.h:433:5: warning: '<anonymous>.absl::lts_20211102::inlined_vector_internal::Storage<int, 1, std::allocator<int> >::data_' is used uninitialized in this function [-Wuninitialized]
  433 |     data_ = other_storage.data_;
      |     ^~~~~
external/com_google_absl/absl/container/internal/inlined_vector.h: In constructor 'riegeli::RecordReaderBase::RecordReaderBase(riegeli::Closed)':
external/com_google_absl/absl/container/internal/inlined_vector.h:433:5: warning: '<anonymous>.absl::lts_20211102::inlined_vector_internal::Storage<int, 1, std::allocator<int> >::data_' is used uninitialized in this function [-Wuninitialized]
  433 |     data_ = other_storage.data_;
      |     ^~~~~
external/com_google_absl/absl/container/internal/inlined_vector.h: In member function 'void riegeli::RecordReaderBase::Reset(riegeli::Closed)':
external/com_google_absl/absl/container/internal/inlined_vector.h:433:5: warning: '<anonymous>.absl::lts_20211102::inlined_vector_internal::Storage<int, 1, std::allocator<int> >::data_' is used uninitialized in this function [-Wuninitialized]
  433 |     data_ = other_storage.data_;
      |     ^~~~~
Target //:print_names_and_sources up-to-date:
  bazel-bin/print_names_and_sources
INFO: Elapsed time: 149.233s, Critical Path: 30.23s
INFO: 716 processes: 21 internal, 695 processwrapper-sandbox.
INFO: Build completed successfully, 716 total actions
INFO: Build completed successfully, 716 total actions
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/execroot/__main__/bazel-out/k8-opt/bin/print_names_and_sources.runfiles/__main__/print_names_and_sources.py", line 46, in <module>
    _print_names_and_sources(sys.argv[1:])
  File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/execroot/__main__/bazel-out/k8-opt/bin/print_names_and_sources.runfiles/__main__/print_names_and_sources.py", line 39, in _print_names_and_sources
    for problem in _all_problems(filenames):
  File "/root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/execroot/__main__/bazel-out/k8-opt/bin/print_names_and_sources.runfiles/__main__/print_names_and_sources.py", line 32, in _all_problems
    reader = riegeli.RecordReader(io.FileIO(filename, mode='rb'),)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\code_contests-main/tmp/dm-code_contests/code_contests_valid.riegeli'`

**Comment by Amandaynzhou** [comment]
> The C++ sandbox is significantly more complicated, and more coupled with internal tools, so while we may release it in the future we currently can't promise anything. I think any kind of sandbox will work though; the main purpose of releasing solution testing is to demonstrate how the output checking works in case it isn't clear from the paper, rather than releasing all the sandboxes we use.
> 
> That said, I think we'd welcome pull requests to add a C++ sandbox (and also giving instructions for colab, other OSs, a docker image, etc. as asked in your last question)

Hi! 
Is there any plan to release the c++ sandbox currently?
